// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:0490776c-3aac-4bc3-88a4-2c8fd4a68aab",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_A6dJ0WrMm",
    "aws_user_pools_web_client_id": "1nvu5vhbgg9kfkq2qulv8f1rrk",
    "oauth": {
        "domain": "drawpass-local.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://3n5bnbfya5cmzp72ghppny7thu.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
